### ISSUE TITLE
Compilation error : toml++/toml.h: No such file or directory

### ISSUE THREAD

**Issue by kaminosekai54** [champost/DECX#3] opened 2022-04-20 10:09 UTC
Hi, 
I'm trying to run DECX on WSL (windows subsystem for linux) but I get an error while compiling : 
![image](https://user-images.githubusercontent.com/66258141/164203791-3e37cf3a-fb99-4f4b-b5fa-bd724e175f5d.png)

I installed all dependencies and followed the instruction in the readme file, here is the command I used : 
sudo apt-get install gfortran
sudo apt-get install libgsl-dev
sudo apt-get install libboost-dev
sudo apt-get install liblapack-dev
sudo apt-get install -y cmake
git clone --recursive https://github.com/champost/DECX
cd DECX
mkdir build
cd build
sudo cmake ../src
sudo make -j $(nproc)

Could you please help me.

**Comment by iago-lito** [comment] 2022-04-22 17:15
Hi @kaminosekai54 ! ~~It seems that TOML sources did not download correctly. I am not sure why~~, but before I investigate, maybe you would like to try one of the first two installation options described [here](https://github.com/champost/DECX#build-instructions)?

Docker and Singularity are expressely designed to avoid all these annoyances you can have while building on your own :)

So, here is my first recommandation:
- either install [singularity](https://sylabs.io/guides/3.0/user-guide/index.html) on your machine then run the following:

```
curl -L https://github.com/champost/DECX/releases/latest/download/singularity.def > decx_singularity.def
sudo singularity build decx.sif decx_singularity.def
./decx.sif my_config_file.toml
```

- or install [docker](https://www.docker.com/) and use:
```
docker buildx build -t decx https://github.com/champost/DECX/releases/latest/download/Dockerfile
docker run --rm -it -v ${PWD}:/home/decx decx my_config.file.toml
```

I'll leave the issue open. Don't hesitate to come back if things continue to go wrong :)

**Comment by iago-lito** [comment] 2022-04-23 02:06
For what it's worth, I can tell that there is a least something wrong with the last few commands. Maybe try :
```bash
mkdir build
cd build
cmake .. # not ../src & no need for sudo
make -j $(nproc) # no need for sudo
```
instead ? This is a mistake in the README. I'll update it asap.

**Comment by iago-lito** [comment] 2022-04-23 07:17
Readme updated in [4f7f518](https://github.com/champost/DECX/commit/4f7f5187226883160987546ff0d3f60cb061dc9c). You may be interested in the following changes:

- Configuration line (use release mode to get optimized binary):
```
cmake -DCMAKE_BUILD_TYPE=Release ..
```
- Additional prerequisite (whose `GSL` depends on I think): [OpenBlas](https://www.openblas.net/). From what I understand, having `GSL` depending on `OpenBlas` instead of `Blas` enables parallel calculations within DECX and improves performances by a factor proportional to `$(nproc)`. To check that it's working as expected on your side:
    - Run DECX and check that all your CPU cores are mobilized during inference.
    - And/Or check that you have something similar to the following output:
```
$ ldd build/decx | grep blas
libgslcblas.so.0 => /usr/lib/libgslcblas.so.0 (0x00007fb5a55df000)
libopenblas.so.3 => /usr/lib/libopenblas.so.3 (0x00007fb5a4228000)
```

In any case, I'm still recommending that you use the __Docker or Singularity__ containerized versions, which should yield much less trouble in the long run because you won't have to deal with all the above kind of details ;)

**Comment by kaminosekai54** [comment] 2022-04-25 15:40
Thanks a lot for your answers, so after seeing the update on the readme,  I retried all installation, but nothing seams to work 👍 
When I tried to build from source, the error isn't the same 

When I run : 
cmake -DCMAKE_BUILD_TYPE=Release ..

![image](https://user-images.githubusercontent.com/66258141/165121531-8d92617e-9f87-4220-83f7-17ac9ad14f38.png)

It doesn't find the package, even it's installed 

I can "delay" the error by giving the path to cmake 👍    cmake -DBLAS_LIBRARIES=$LIB/libopenblas -DCMAKE_BUILD_TYPE=Release ..

I get : 
![image](https://user-images.githubusercontent.com/66258141/165122777-1f723bab-028a-485d-93f5-6bbcfae4220d.png)


So I tried the two other installing methode, but I get the same error at the end : 

singularity : 

The installation went with out any problem, but when I'm trying to execute : 

./decx.sif my_config_file.toml


I get 

![image](https://user-images.githubusercontent.com/66258141/165123364-01d9ada6-a9b8-49dd-8537-9abab8a5f312.png)


Same thing using docker : 
docker run --rm -it -v ${PWD}:/home/decx decx my_config.file.toml

I get 
![image](https://user-images.githubusercontent.com/66258141/165123819-deeaa966-94e5-475f-b99d-f28dae43b727.png)


Sorry for those, I guess unexpected error.

But to confirm, yes, I'm using wsl2 as requiered by singularity and docker.

Thanks for your time

**Comment by iago-lito** [comment] 2022-04-26 08:04
Hello @kaminosekai54 ! Well, good news : your last two examples with singularity and docker are actually __WORKING__ ^ ^
The error you see
```
Failed to parse DECX config file:
  File could not be opened for reading
```
.. is just DECX warning you that the file `my_config.file.toml` could not be found. This is expected behaviour. Are you sure that this file actually exists?

**Comment by iago-lito** [comment] 2022-04-26 08:15
Regarding your problem with `LAPACK` and `BLAST`. My only guess is that maybe your distribution (WSL/Ubuntuish-Windows-ish) stores these libraries in non-standard locations that `cmake` cannot find on its own? You were on the right track passing the paths explicitly with *e.g.* `-DBLAS_LIBRARIES`.. and maybe there is a similar `-DLAPACK_LIBRARIES` that I am unaware about?

Anyway, I known that compilation may be a nightmare, which is the reason why I recommend using Singularity or Docker : they perform the compilation for you in a controlled environment so you don't have to think about all this.. and look, it worked :)

Now you just need to pass the correct configuration files. Are you actually familiar with DECX usage? (to my knowledge it is undocumented yet)

**Comment by kaminosekai54** [comment] 2022-04-26 08:54
Hello, ok, thanks, good news.

No, I'm fully unfamiliar with DECX.
But from what I understood, the configuration file that I have to pass should look like the one in the test folder in the .zip source.
But yes, I admet that guide lines on how to use it would be appreciable.

But any way, thanks a lot for your rupport :)

**Comment by iago-lito** [comment] 2022-04-26 09:41
Ok. At this point I need to explain the current state of the project. DECX is a program that (apparently) runs well, but is very difficult to install and to use. It was written years ago by the original author. And I have been working on it for a few months only, not to change or upgrade its internals (yet), but only to improve the installation experience and the ease of use.

As a matter of fact, there is currently no documentation about the new usage (several carefully crafted files are needed to make DECX run correctly), and I cannot write a useful documentation yet because it is not currently stable and I only have superficial knowledge about what's going on inside the model. In a nutshell, once you have successfully installed DECX, I cannot help you much with the actual usage :\

My recommendation then is to get in touch with colleagues who already know how to use it, or with Fabien Condamine and his team here in Montpellier, so you can share knowledge and I can keep on improving DECX experience. Please don't hesitate to reach us by e-mail from now on :)

Closing this because the compilation eventually succeeded on your machine.

**Closed as completed by iago-lito** 2022-04-26 09:41 UTC

**Comment by PhilThieme** [comment] 2023-05-17 12:11
Hi Iago,

I just started using DECX with Docker. While it is running, I get the same error message as kaminosekai54. Apparently, the conf.toml file can't be found, although both directory and file are correct. 

Where does decx search for the toml file? Maybe this will help to figure out how to read the file correctly.

Cheers,
Philipp

**Comment by iago-lito** [comment] 2023-06-07 07:34
Hi @PhilThieme. DECX searches the config file from the location you run the executable. I can't reproduce your problem on my side. Can you please post a mwe so I can investigate? Or explain what's your non-working directory structure, the command you use and the output you get?

**Comment by PhilThieme** [comment] 2023-06-07 08:37
![Clipboard](https://github.com/champost/DECX/assets/99792079/feade1c6-ddc8-4355-b156-4da4c3aceca4)

I used the example files provided in the repository. Both the executable and the toml file are in the same folder.
Do you need any futher information?

**Comment by iago-lito** [comment] 2023-06-16 12:57
I see. Well, unlike singularity, the current folder is not automatically mounted within the container with docker. Have you tried with the command from the [README.md](https://github.com/champost/DECX/blob/main/README.md) instead?

```sh
> docker run --rm -it -v ${PWD}:/home/decx decx config.toml
```

Maybe the command will slightly differ on windows, but the idea is that DEXC expects the current folder to be mounted as `/home/decx` within the container.
